# Generated by Django 4.1.11 on 2023-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_about_about_cafe_about_name_888815_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='cafe_topic_name_2181a3_idx'),
        ),
    ]
