# Generated by Django 4.1.11 on 2023-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_about_delete_topic_about_cafe_about_name_888815_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/%Y/%m/%d'),
        ),
    ]
