# Generated by Django 4.1.11 on 2023-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_about_number_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
