# Generated by Django 4.1.11 on 2023-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_about_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
