# Generated by Django 4.1.11 on 2023-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_about_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='special/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='special',
            index=models.Index(fields=['name'], name='cafe_specia_name_35bd18_idx'),
        ),
    ]
