# Generated by Django 4.1.11 on 2023-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_special_remove_about_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
