# Generated by Django 4.1.11 on 2023-09-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_special_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='special',
            name='cafe_specia_name_35bd18_idx',
        ),
        migrations.RemoveField(
            model_name='special',
            name='number',
        ),
    ]
