# Generated by Django 4.1.11 on 2023-09-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
